// ─── Man Pages ──────────────────────────────────────────────────────────────

export const MAN_PAGES: Record<string, string[]> = {
  goto: [
    "NAME",
    "    goto - navigate to a GradeFlow page",
    "",
    "SYNOPSIS",
    "    goto <page>",
    "",
    "DESCRIPTION",
    "    Instantly navigate to any page in the GradeFlow workspace.",
    "    This is the fastest way to move through the OS.",
    "",
    "PAGES",
    "    dashboard     Main workspace dashboard",
    "    placement     Placement intelligence hub",
    "    career        Career roadmap builder",
    "    forecast      Academic forecasting engine",
    "    backlog       Backlog recovery tracker",
    "    calculator    CGPA/SGPA calculator",
    "    attendance    Attendance management",
    "    planner       Study planner & timetable",
    "    overview      Academic overview",
    "    identity      Academic identity card",
    "    records       Academic records",
    "    ledger        Grade ledger",
    "    timeline      Academic timeline",
    "",
    "EXAMPLES",
    "    goto dashboard",
    "    goto placement",
    "    goto career",
  ],
  back: [
    "NAME",
    "    back - navigate to the previous page",
    "",
    "SYNOPSIS",
    "    back",
    "",
    "DESCRIPTION",
    "    Returns to the previously visited page.",
    "    Equivalent to pressing the browser back button.",
  ],
  home: [
    "NAME",
    "    home - navigate to the landing page",
    "",
    "SYNOPSIS",
    "    home",
    "",
    "DESCRIPTION",
    "    Returns to the GradeFlow landing page.",
  ],
  open: [
    "NAME",
    "    open - open a workspace panel",
    "",
    "SYNOPSIS",
    "    open <panel>",
    "",
    "DESCRIPTION",
    "    Opens a specific workspace side panel.",
    "",
    "PANELS",
    "    predictor       Grade predictor panel",
    "    strategy        Strategy advisor panel",
    "    backlog         Backlog management panel",
    "    interventions   AI intervention panel",
    "",
    "EXAMPLES",
    "    open predictor",
    "    open strategy",
  ],
  whoami: [
    "NAME",
    "    whoami - display current user metrics",
    "",
    "SYNOPSIS",
    "    whoami",
    "",
    "DESCRIPTION",
    "    Displays the current academic and career metrics.",
    "    In sandbox mode, shows overridden sandbox values.",
    "",
    "OUTPUT",
    "    CGPA, Active Backlogs, Target Role, Skills",
  ],
  status: [
    "NAME",
    "    status - quick system status",
    "",
    "SYNOPSIS",
    "    status",
    "",
    "DESCRIPTION",
    "    Shows a compact one-line status of your academic state.",
    "    Includes CGPA, backlogs, current mode, and risk level.",
  ],
  neofetch: [
    "NAME",
    "    neofetch - system information display",
    "",
    "SYNOPSIS",
    "    neofetch",
    "",
    "DESCRIPTION",
    "    Displays a beautiful ASCII art dashboard with your",
    "    complete academic system information including CGPA,",
    "    backlogs, semester, credits, mode, target role, and",
    "    risk level.",
    "",
    "    Automatically displayed on first terminal open.",
  ],
  ls: [
    "NAME",
    "    ls - list academic data",
    "",
    "SYNOPSIS",
    "    ls subjects",
    "    ls backlogs",
    "",
    "DESCRIPTION",
    "    Lists academic data in a formatted table.",
    "",
    "ARGUMENTS",
    "    subjects    List all enrolled courses with grades",
    "    backlogs    List only courses with active backlogs",
    "",
    "EXAMPLES",
    "    ls subjects",
    "    ls backlogs",
  ],
  cat: [
    "NAME",
    "    cat - display course details",
    "",
    "SYNOPSIS",
    "    cat <course_code>",
    "",
    "DESCRIPTION",
    "    Shows detailed information about a specific course",
    "    including grade, CIE marks, attendance, and credits.",
    "",
    "EXAMPLES",
    "    cat CS301",
    "    cat MA201",
  ],
  analyze: [
    "NAME",
    "    analyze - run diagnostic analysis",
    "",
    "SYNOPSIS",
    "    analyze --profile",
    "    analyze --risk",
    "    analyze --attendance",
    "",
    "FLAGS",
    "    --profile      Full academic profile diagnostic",
    "    --risk         Risk assessment breakdown",
    "    --attendance   Per-subject attendance analysis",
    "",
    "DESCRIPTION",
    "    Runs analytical diagnostics on your academic data.",
    "    Uses current values, or sandbox values if active.",
  ],
  sandbox: [
    "NAME",
    "    sandbox - enter/exit simulation mode",
    "",
    "SYNOPSIS",
    "    sandbox enter",
    "    sandbox exit",
    "",
    "DESCRIPTION",
    "    Sandbox mode lets you override your real metrics",
    "    with hypothetical values for what-if analysis.",
    "    The terminal border turns red to indicate sandbox.",
    "",
    "    Use 'set cgpa' and 'set backlogs' to override values.",
    "",
    "SEE ALSO",
    "    set, analyze",
  ],
  set: [
    "NAME",
    "    set - override sandbox metrics",
    "",
    "SYNOPSIS",
    "    set cgpa <value>",
    "    set backlogs <value>",
    "",
    "DESCRIPTION",
    "    Overrides academic metrics while in sandbox mode.",
    "    Has no effect outside of sandbox mode.",
    "",
    "EXAMPLES",
    "    set cgpa 8.5",
    "    set backlogs 2",
    "",
    "SEE ALSO",
    "    sandbox",
  ],
  alias: [
    "NAME",
    "    alias - create a command shortcut",
    "",
    "SYNOPSIS",
    "    alias <name>=<command>",
    "",
    "DESCRIPTION",
    "    Creates a custom shortcut for any command.",
    "    Aliases persist for the current session.",
    "",
    "EXAMPLES",
    "    alias gp=goto placement",
    "    alias s=status",
    "    alias gd=goto dashboard",
    "",
    "SEE ALSO",
    "    unalias, aliases",
  ],
  unalias: [
    "NAME",
    "    unalias - remove a command shortcut",
    "",
    "SYNOPSIS",
    "    unalias <name>",
    "",
    "DESCRIPTION",
    "    Removes a previously created alias.",
    "",
    "SEE ALSO",
    "    alias, aliases",
  ],
  aliases: [
    "NAME",
    "    aliases - list all command shortcuts",
    "",
    "SYNOPSIS",
    "    aliases",
    "",
    "DESCRIPTION",
    "    Displays all currently defined aliases.",
  ],
  theme: [
    "NAME",
    "    theme - change terminal appearance",
    "",
    "SYNOPSIS",
    "    theme <name>",
    "",
    "THEMES",
    "    default       Dark with purple/blue accents",
    "    matrix        Green-on-black hacker aesthetic",
    "    dracula       Rich purple palette",
    "    catppuccin    Warm pastel tones",
    "",
    "EXAMPLES",
    "    theme matrix",
    "    theme dracula",
  ],
  history: [
    "NAME",
    "    history - show command history",
    "",
    "SYNOPSIS",
    "    history",
    "",
    "DESCRIPTION",
    "    Displays a numbered list of all commands",
    "    executed in the current session.",
  ],
  export: [
    "NAME",
    "    export - export terminal session",
    "",
    "SYNOPSIS",
    "    export session",
    "",
    "DESCRIPTION",
    "    Copies the entire terminal history to the clipboard",
    "    as a plain text file. Useful for sharing or debugging.",
  ],
  man: [
    "NAME",
    "    man - display command manual",
    "",
    "SYNOPSIS",
    "    man <command>",
    "",
    "DESCRIPTION",
    "    Displays the detailed manual page for a command.",
    "    Includes usage, flags, examples, and related commands.",
    "",
    "EXAMPLES",
    "    man goto",
    "    man analyze",
    "    man sandbox",
  ],
  clear: [
    "NAME",
    "    clear - clear terminal",
    "",
    "SYNOPSIS",
    "    clear",
    "",
    "DESCRIPTION",
    "    Clears all terminal output history.",
    "    Keyboard shortcut: Ctrl+K",
  ],
  help: [
    "NAME",
    "    help - list available commands",
    "",
    "SYNOPSIS",
    "    help",
    "",
    "DESCRIPTION",
    "    Shows all available commands organized by category.",
    "    For detailed info on a specific command, use 'man <cmd>'.",
  ],
  matrix: [
    "NAME",
    "    matrix - digital rain animation",
    "",
    "SYNOPSIS",
    "    matrix",
    "",
    "DESCRIPTION",
    "    Displays the iconic Matrix digital rain effect",
    "    inside the terminal. Press any key to stop.",
  ],
  cowsay: [
    "NAME",
    "    cowsay - ASCII cow with message",
    "",
    "SYNOPSIS",
    "    cowsay <message>",
    "",
    "DESCRIPTION",
    "    Displays an ASCII art cow saying your message.",
    "",
    "EXAMPLES",
    "    cowsay hello world",
    "    cowsay I love GradeFlow",
  ],
  fortune: [
    "NAME",
    "    fortune - random motivational quote",
    "",
    "SYNOPSIS",
    "    fortune",
    "",
    "DESCRIPTION",
    "    Displays a random motivational or academic quote",
    "    to brighten your study session.",
  ],
  uptime: [
    "NAME",
    "    uptime - session duration",
    "",
    "SYNOPSIS",
    "    uptime",
    "",
    "DESCRIPTION",
    "    Shows how long the current terminal session has been",
    "    active since the page was loaded.",
  ],
};
